---
# tasks file for cisco-setup
- name: hello
  debug:
    msg: "Hello!"

- name: GATHER FACTS
  ios_facts:
    gather_subset: all
  register: facts

- name: print facts
  debug:
    msg: "{{ facts }}"
